from rich import box
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

console = Console()

_SEVERITY_STYLE = {
    "high":   "bold red",
    "medium": "yellow",
    "low":    "cyan",
}


def _score_style(score: int) -> str:
    if score >= 8:
        return "bold green"
    if score >= 5:
        return "bold yellow"
    return "bold red"


def _severity_badge(severity: str) -> Text:
    style = _SEVERITY_STYLE.get(severity.lower(), "white")
    return Text(f" {severity.upper()} ", style=f"reverse {style}")


def _bugs_table(bugs: list) -> Table:
    table = Table(box=box.SIMPLE_HEAD, show_header=True, header_style="bold")
    table.add_column("Sev", width=10)
    table.add_column("Line", width=6)
    table.add_column("Issue")

    for bug in bugs:
        line = str(bug.get("line") or "—")
        severity = bug.get("severity", "low")
        table.add_row(
            _severity_badge(severity),
            line,
            bug.get("message", ""),
        )
    return table


def _style_table(issues: list) -> Table:
    table = Table(box=box.SIMPLE_HEAD, show_header=True, header_style="bold")
    table.add_column("Line", width=6)
    table.add_column("Issue")

    for issue in issues:
        line = str(issue.get("line") or "—")
        table.add_row(line, issue.get("message", ""))
    return table


def display_review(review: dict) -> None:
    console.rule("[bold blue]nitpick review[/bold blue]")

    # Summary
    summary = review.get("summary", "No summary provided.")
    console.print(Panel(summary, title="Summary", border_style="blue", padding=(0, 1)))

    # Score
    score = review.get("score", 0)
    score_text = Text()
    score_text.append("  Score  ", style="bold")
    score_text.append(f"  {score} / 10  ", style=f"reverse {_score_style(score)}")
    console.print(score_text, justify="left")
    console.print()

    # Bugs
    bugs = review.get("bugs") or []
    if bugs:
        console.print(Panel(
            _bugs_table(bugs),
            title=f"[bold red]Bugs[/bold red] ({len(bugs)})",
            border_style="red",
            padding=(0, 1),
        ))
    else:
        console.print(Panel("[green]No bugs found.[/green]", title="Bugs", border_style="green", padding=(0, 1)))

    # Style issues
    style_issues = review.get("style_issues") or []
    if style_issues:
        console.print(Panel(
            _style_table(style_issues),
            title=f"[bold yellow]Style Issues[/bold yellow] ({len(style_issues)})",
            border_style="yellow",
            padding=(0, 1),
        ))

    # Suggestions
    suggestions = review.get("suggestions") or []
    if suggestions:
        suggestions_text = "\n".join(f"  • {s}" for s in suggestions)
        console.print(Panel(
            suggestions_text,
            title="[bold cyan]Suggestions[/bold cyan]",
            border_style="cyan",
            padding=(0, 1),
        ))

    console.rule()


_SEVERITY_EMOJI = {"high": "🔴", "medium": "🟡", "low": "🟢"}
_SCORE_EMOJI = {range(1, 5): "🔴", range(5, 8): "🟡", range(8, 11): "🟢"}


def _score_emoji(score: int) -> str:
    for r, emoji in _SCORE_EMOJI.items():
        if score in r:
            return emoji
    return "⚪"


def markdown_review(review: dict) -> str:
    lines = ["## nitpick review", ""]

    summary = review.get("summary", "No summary provided.")
    lines += [f"**Summary:** {summary}", ""]

    score = review.get("score", 0)
    lines += [f"**Score:** {score}/10 {_score_emoji(score)}", ""]

    bugs = review.get("bugs") or []
    if bugs:
        lines += [f"### 🐛 Bugs ({len(bugs)})", ""]
        lines += ["| Severity | Line | Issue |", "|----------|------|-------|"]
        for bug in bugs:
            sev = bug.get("severity", "low")
            emoji = _SEVERITY_EMOJI.get(sev.lower(), "⚪")
            line = str(bug.get("line") or "—")
            msg = bug.get("message", "").replace("|", "\\|")
            lines.append(f"| {emoji} {sev.upper()} | {line} | {msg} |")
        lines.append("")
    else:
        lines += ["### 🐛 Bugs", "", "No bugs found. ✅", ""]

    style_issues = review.get("style_issues") or []
    if style_issues:
        lines += [f"### 🎨 Style Issues ({len(style_issues)})", ""]
        lines += ["| Line | Issue |", "|------|-------|"]
        for issue in style_issues:
            line = str(issue.get("line") or "—")
            msg = issue.get("message", "").replace("|", "\\|")
            lines.append(f"| {line} | {msg} |")
        lines.append("")

    suggestions = review.get("suggestions") or []
    if suggestions:
        lines += ["### 💡 Suggestions", ""]
        for s in suggestions:
            lines.append(f"- {s}")
        lines.append("")

    lines += ["---", "*Generated by [nitpick](https://github.com/kellybecker/nitpick)*"]
    return "\n".join(lines)
